set(SUBDIR_NAME Dialogs)

# Include the Utilities sources
include(${${PROJECT_NAME}_SOURCE_DIR}/SIMPLVtkLib/${SUBDIR_NAME}/Utilities/SourceList.cmake)

# --------------------------------------------------------------------
# Any Class that inherits from QObject, either directly or through the heirarchy needs to have its header listed here
set(${PROJECT_NAME}_${SUBDIR_NAME}_Moc_HDRS
  ${${PROJECT_NAME}_SOURCE_DIR}/SIMPLVtkLib/${SUBDIR_NAME}/AbstractImportMontageDialog.h
  ${${PROJECT_NAME}_SOURCE_DIR}/SIMPLVtkLib/${SUBDIR_NAME}/FijiListWidget.h
  ${${PROJECT_NAME}_SOURCE_DIR}/SIMPLVtkLib/${SUBDIR_NAME}/ImportDREAM3DMontageDialog.h
  ${${PROJECT_NAME}_SOURCE_DIR}/SIMPLVtkLib/${SUBDIR_NAME}/ImportFijiMontageDialog.h
  ${${PROJECT_NAME}_SOURCE_DIR}/SIMPLVtkLib/${SUBDIR_NAME}/ImportGenericMontageDialog.h
  ${${PROJECT_NAME}_SOURCE_DIR}/SIMPLVtkLib/${SUBDIR_NAME}/ImportRobometMontageDialog.h
  ${${PROJECT_NAME}_SOURCE_DIR}/SIMPLVtkLib/${SUBDIR_NAME}/ImportZeissMontageDialog.h
  ${${PROJECT_NAME}_SOURCE_DIR}/SIMPLVtkLib/${SUBDIR_NAME}/LoadHDF5FileDialog.h
  ${${PROJECT_NAME}_SOURCE_DIR}/SIMPLVtkLib/${SUBDIR_NAME}/RobometListWidget.h
  ${${PROJECT_NAME}_SOURCE_DIR}/SIMPLVtkLib/${SUBDIR_NAME}/TileListWidget.h
  ${${PROJECT_NAME}_SOURCE_DIR}/SIMPLVtkLib/${SUBDIR_NAME}/ZeissListWidget.h
  )
# --------------------------------------------------------------------
# Run Qts automoc program to generate some source files that get compiled
set_source_files_properties( ${${PROJECT_NAME}_${SUBDIR_NAME}_Generated_MOC_SRCS} PROPERTIES GENERATED TRUE)
set_source_files_properties( ${${PROJECT_NAME}_${SUBDIR_NAME}_Generated_MOC_SRCS} PROPERTIES HEADER_FILE_ONLY TRUE)

set(${PROJECT_NAME}_${SUBDIR_NAME}_HDRS

)

set(${PROJECT_NAME}_${SUBDIR_NAME}_SRCS
${${PROJECT_NAME}_SOURCE_DIR}/SIMPLVtkLib/${SUBDIR_NAME}/AbstractImportMontageDialog.cpp
${${PROJECT_NAME}_SOURCE_DIR}/SIMPLVtkLib/${SUBDIR_NAME}/FijiListWidget.cpp
${${PROJECT_NAME}_SOURCE_DIR}/SIMPLVtkLib/${SUBDIR_NAME}/ImportDREAM3DMontageDialog.cpp
${${PROJECT_NAME}_SOURCE_DIR}/SIMPLVtkLib/${SUBDIR_NAME}/ImportFijiMontageDialog.cpp
${${PROJECT_NAME}_SOURCE_DIR}/SIMPLVtkLib/${SUBDIR_NAME}/ImportGenericMontageDialog.cpp
${${PROJECT_NAME}_SOURCE_DIR}/SIMPLVtkLib/${SUBDIR_NAME}/ImportRobometMontageDialog.cpp
${${PROJECT_NAME}_SOURCE_DIR}/SIMPLVtkLib/${SUBDIR_NAME}/ImportZeissMontageDialog.cpp
${${PROJECT_NAME}_SOURCE_DIR}/SIMPLVtkLib/${SUBDIR_NAME}/LoadHDF5FileDialog.cpp
${${PROJECT_NAME}_SOURCE_DIR}/SIMPLVtkLib/${SUBDIR_NAME}/RobometListWidget.cpp
${${PROJECT_NAME}_SOURCE_DIR}/SIMPLVtkLib/${SUBDIR_NAME}/TileListWidget.cpp
${${PROJECT_NAME}_SOURCE_DIR}/SIMPLVtkLib/${SUBDIR_NAME}/ZeissListWidget.cpp
)

# The UI files As generated by Qt Designer
SET(${PROJECT_NAME}_${SUBDIR_NAME}_UIS
  ${${PROJECT_NAME}_SOURCE_DIR}/SIMPLVtkLib/${SUBDIR_NAME}/UI_Files/FijiListWidget.ui
  ${${PROJECT_NAME}_SOURCE_DIR}/SIMPLVtkLib/${SUBDIR_NAME}/UI_Files/ImportDREAM3DMontageDialog.ui
  ${${PROJECT_NAME}_SOURCE_DIR}/SIMPLVtkLib/${SUBDIR_NAME}/UI_Files/ImportFijiMontageDialog.ui
  ${${PROJECT_NAME}_SOURCE_DIR}/SIMPLVtkLib/${SUBDIR_NAME}/UI_Files/ImportGenericMontageDialog.ui
  ${${PROJECT_NAME}_SOURCE_DIR}/SIMPLVtkLib/${SUBDIR_NAME}/UI_Files/ImportRobometMontageDialog.ui
  ${${PROJECT_NAME}_SOURCE_DIR}/SIMPLVtkLib/${SUBDIR_NAME}/UI_Files/ImportZeissMontageDialog.ui
  ${${PROJECT_NAME}_SOURCE_DIR}/SIMPLVtkLib/${SUBDIR_NAME}/UI_Files/LoadHDF5FileDialog.ui
  ${${PROJECT_NAME}_SOURCE_DIR}/SIMPLVtkLib/${SUBDIR_NAME}/UI_Files/RobometListWidget.ui
  ${${PROJECT_NAME}_SOURCE_DIR}/SIMPLVtkLib/${SUBDIR_NAME}/UI_Files/TileListWidget.ui
  ${${PROJECT_NAME}_SOURCE_DIR}/SIMPLVtkLib/${SUBDIR_NAME}/UI_Files/ZeissListWidget.ui
)

cmp_IDE_GENERATED_PROPERTIES("${SUBDIR_NAME}/UI_Files" "${${PROJECT_NAME}_${SUBDIR_NAME}_UIS}" "")

# this will run uic on .ui files:
QT5_WRAP_UI( ${PROJECT_NAME}_${SUBDIR_NAME}_Generated_UI_HDRS ${${PROJECT_NAME}_${SUBDIR_NAME}_UIS} )
foreach(h ${${PROJECT_NAME}_${SUBDIR_NAME}_Generated_UI_HDRS})
  set_property(SOURCE ${h} PROPERTY SKIP_AUTOMOC ON)
endforeach()

cmp_IDE_SOURCE_PROPERTIES( "${SUBDIR_NAME}" "${${PROJECT_NAME}_${SUBDIR_NAME}_HDRS};${${PROJECT_NAME}_${SUBDIR_NAME}_Moc_HDRS}" "${${PROJECT_NAME}_${SUBDIR_NAME}_SRCS}" "${PROJECT_INSTALL_HEADERS}")
cmp_IDE_SOURCE_PROPERTIES( "Generated/${SUBDIR_NAME}" "" "${${PROJECT_NAME}_${SUBDIR_NAME}_Generated_MOC_SRCS}" "0")

#-- Put the generated files into their own group for IDEs
cmp_IDE_GENERATED_PROPERTIES("Generated/ui" "${${PROJECT_NAME}_${SUBDIR_NAME}_Generated_UI_HDRS}" "")
cmp_IDE_GENERATED_PROPERTIES("Generated/moc" "${${PROJECT_NAME}_${SUBDIR_NAME}_Generated_MOC_SRCS}" "")

set(${PROJECT_NAME}_${SUBDIR_NAME}_HDRS
  ${${PROJECT_NAME}_${SUBDIR_NAME}_HDRS}
  ${${PROJECT_NAME}_${SUBDIR_NAME}_Moc_HDRS}  # Add the headers that get Moc'ed here so they show up in solutions/IDEs/Project files
)

set(${PROJECT_NAME}_${SUBDIR_NAME}_SRCS
  ${${PROJECT_NAME}_${SUBDIR_NAME}_SRCS}
  ${${PROJECT_NAME}_${SUBDIR_NAME}_Generated_MOC_SRCS}
)

include_directories(${${PROJECT_NAME}_SOURCE_DIR}/SIMPLVtkLib/${SUBDIR_NAME}/UI_Files)