
set(${PROJECT_NAME}_QML_HDRS
  ${${PROJECT_NAME}_SOURCE_DIR}/SIMPLVtkLib/QML/VSQmlFboRenderer.h
  ${${PROJECT_NAME}_SOURCE_DIR}/SIMPLVtkLib/QML/VSQmlRenderWindow.h
  ${${PROJECT_NAME}_SOURCE_DIR}/SIMPLVtkLib/QML/VSQmlVtkView.h
  ${${PROJECT_NAME}_SOURCE_DIR}/SIMPLVtkLib/QML/VSQuickWidget.h
  ${${PROJECT_NAME}_SOURCE_DIR}/SIMPLVtkLib/QML/QmlMacros.h
  ${${PROJECT_NAME}_SOURCE_DIR}/SIMPLVtkLib/QML/VSQmlLoader.h
)

set(${PROJECT_NAME}_QML_SRCS
  ${${PROJECT_NAME}_SOURCE_DIR}/SIMPLVtkLib/QML/VSQmlFboRenderer.cpp
  ${${PROJECT_NAME}_SOURCE_DIR}/SIMPLVtkLib/QML/VSQmlRenderWindow.cpp
  ${${PROJECT_NAME}_SOURCE_DIR}/SIMPLVtkLib/QML/VSQmlVtkView.cpp
  ${${PROJECT_NAME}_SOURCE_DIR}/SIMPLVtkLib/QML/VSQuickWidget.cpp
  ${${PROJECT_NAME}_SOURCE_DIR}/SIMPLVtkLib/QML/VSQmlLoader.cpp
)


cmp_IDE_SOURCE_PROPERTIES( "${PROJECT_NAME}/QML" "${${PROJECT_NAME}_QML_HDRS}" "${${PROJECT_NAME}_QML_SRCS}" "0")
