
set(VS_SIMPLBridge_SRCS
	${${PROJECT_NAME}_SOURCE_DIR}/SIMPLVtkLib/SIMPLBridge/SIMPLVtkBridge.cpp
	${${PROJECT_NAME}_SOURCE_DIR}/SIMPLVtkLib/SIMPLBridge/VSEdgeGeom.cpp
	${${PROJECT_NAME}_SOURCE_DIR}/SIMPLVtkLib/SIMPLBridge/VSQuadGeom.cpp
	${${PROJECT_NAME}_SOURCE_DIR}/SIMPLVtkLib/SIMPLBridge/VSTetrahedralGeom.cpp
	${${PROJECT_NAME}_SOURCE_DIR}/SIMPLVtkLib/SIMPLBridge/VSTriangleGeom.cpp
	${${PROJECT_NAME}_SOURCE_DIR}/SIMPLVtkLib/SIMPLBridge/VSVertexGeom.cpp
)

set(VS_SIMPLBridge_HDRS
	#${${PROJECT_NAME}_SOURCE_DIR}/SIMPLVtkLib/SIMPLBridge/SIMPLVtkArray.hpp
	${${PROJECT_NAME}_SOURCE_DIR}/SIMPLVtkLib/SIMPLBridge/SIMPLVtkBridge.h
	${${PROJECT_NAME}_SOURCE_DIR}/SIMPLVtkLib/SIMPLBridge/VSEdgeGeom.h
	${${PROJECT_NAME}_SOURCE_DIR}/SIMPLVtkLib/SIMPLBridge/VSQuadGeom.h
	${${PROJECT_NAME}_SOURCE_DIR}/SIMPLVtkLib/SIMPLBridge/VSTetrahedralGeom.h
	${${PROJECT_NAME}_SOURCE_DIR}/SIMPLVtkLib/SIMPLBridge/VSTriangleGeom.h
	${${PROJECT_NAME}_SOURCE_DIR}/SIMPLVtkLib/SIMPLBridge/VSVertexGeom.h
	${${PROJECT_NAME}_SOURCE_DIR}/SIMPLVtkLib/SIMPLBridge/VtkMacros.h
)

# if(APPLE)
# 	list(APPEND VtkSIMPL_SIMPLBridge_SRCS ${${PROJECT_NAME}_SOURCE_DIR}/SIMPLVtkLib/SIMPLBridge/OSXHiDPIHelper.mm)
# 	list(APPEND VtkSIMPL_SIMPLBridge_HDRS ${${PROJECT_NAME}_SOURCE_DIR}/SIMPLVtkLib/SIMPLBridge/OSXHiDPIHelper.h)
# endif()


cmp_IDE_SOURCE_PROPERTIES( "${PROJECT_NAME}/SIMPLBridge" "${VS_SIMPLBridge_HDRS}" "${VS_SIMPLBridge_SRCS}" "0")
